{
  "uid" : "fc78585efeb0ef08",
  "name" : "针对异常登陆的测试",
  "fullName" : "cases.test_login.TestLogin#test_login_failed",
  "historyId" : "dbeb2a97f887c27b8015e9253b5aa614",
  "time" : {
    "start" : 1609856259602,
    "stop" : 1609856260362,
    "duration" : 760
  },
  "status" : "broken",
  "statusMessage" : "TypeError: 'module' object is not callable",
  "statusTrace" : "self = <allure_commons._allure.fixture object at 0x03A2A550>, args = ()\nkwargs = {}\n\n    def __call__(self, *args, **kwargs):\n        self.parameters = func_parameters(self._fixture_function, *args, **kwargs)\n    \n        with self:\n>           return self._fixture_function(*args, **kwargs)\n\n..\\..\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\site-packages\\allure_commons\\_allure.py:200: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n    @pytest.fixture(scope='function')\n    def refresh_page():\n        \"\"\"\n        用例执行后刷新页面\n        :return:\n        \"\"\"\n        #driver.refresh  此语句在本方法（refresh_page )中不能调用方法handler里面的driver参数，需要将方法handler中的driver定义为全局变量\n        #在执行refresh_page前需要调用其他方法\n        yield    #yield前面无任何语句：在执行完测试用例（函数）前不执行任何语句，用例执行结束后执行被装饰函数中yield之后的语句\n        driver.refresh()   #刷新页面语句\n>       time(3)  #刷新完页面后等待3秒再执行之后的语句\nE       TypeError: 'module' object is not callable\n\ncases\\conftest.py:44: TypeError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "refresh_page",
    "time" : {
      "start" : 1609856259601,
      "stop" : 1609856259601,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "handler",
    "time" : {
      "start" : 1609856242828,
      "stop" : 1609856256063,
      "duration" : 13235
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "TypeError: 'module' object is not callable",
    "statusTrace" : "self = <allure_commons._allure.fixture object at 0x03A2A550>, args = ()\nkwargs = {}\n\n    def __call__(self, *args, **kwargs):\n        self.parameters = func_parameters(self._fixture_function, *args, **kwargs)\n    \n        with self:\n>           return self._fixture_function(*args, **kwargs)\n\n..\\..\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\site-packages\\allure_commons\\_allure.py:200: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n    @pytest.fixture(scope='function')\n    def refresh_page():\n        \"\"\"\n        用例执行后刷新页面\n        :return:\n        \"\"\"\n        #driver.refresh  此语句在本方法（refresh_page )中不能调用方法handler里面的driver参数，需要将方法handler中的driver定义为全局变量\n        #在执行refresh_page前需要调用其他方法\n        yield    #yield前面无任何语句：在执行完测试用例（函数）前不执行任何语句，用例执行结束后执行被装饰函数中yield之后的语句\n        driver.refresh()   #刷新页面语句\n>       time(3)  #刷新完页面后等待3秒再执行之后的语句\nE       TypeError: 'module' object is not callable\n\ncases\\conftest.py:44: TypeError",
    "steps" : [ {
      "name" : "步骤1：登录",
      "time" : {
        "start" : 1609856259608,
        "stop" : 1609856259609,
        "duration" : 1
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "hasContent" : false,
      "shouldDisplayMessage" : false,
      "attachmentsCount" : 0
    } ],
    "attachments" : [ {
      "uid" : "bbc669f10b6ae322",
      "name" : "log",
      "source" : "bbc669f10b6ae322.txt",
      "type" : "text/plain",
      "size" : 5197
    } ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "hasContent" : true,
    "shouldDisplayMessage" : true,
    "attachmentsCount" : 1
  },
  "afterStages" : [ {
    "name" : "refresh_page::0",
    "time" : {
      "start" : 1609856260364,
      "stop" : 1609856260811,
      "duration" : 447
    },
    "status" : "broken",
    "statusMessage" : "TypeError: 'module' object is not callable\n",
    "statusTrace" : "  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 941, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\po_jrj\\cases\\conftest.py\", line 44, in refresh_page\n    time(3)  #刷新完页面后等待3秒再执行之后的语句\n",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : true,
    "shouldDisplayMessage" : true,
    "attachmentsCount" : 0
  }, {
    "name" : "handler::0",
    "time" : {
      "start" : 1609856277827,
      "stop" : 1609856281790,
      "duration" : 3963
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "labels" : [ {
    "name" : "story",
    "value" : "登录模块-异常登陆"
  }, {
    "name" : "epic",
    "value" : "金融界web自动化自测"
  }, {
    "name" : "feature",
    "value" : "金融界web登录模块"
  }, {
    "name" : "tag",
    "value" : "@pytest.mark.usefixtures('refresh_page')"
  }, {
    "name" : "parentSuite",
    "value" : "cases"
  }, {
    "name" : "suite",
    "value" : "test_login"
  }, {
    "name" : "subSuite",
    "value" : "TestLogin"
  }, {
    "name" : "host",
    "value" : "PC-20200718ELAI"
  }, {
    "name" : "thread",
    "value" : "38852-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "cases.test_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "data",
    "value" : "{'name': '登录功能-异常登录-密码错误', 'username': '财友2sna6763', 'password': '654321'}"
  } ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ "@pytest.mark.usefixtures('refresh_page')" ]
  },
  "source" : "fc78585efeb0ef08.json",
  "parameterValues" : [ "{'name': '登录功能-异常登录-密码错误', 'username': '财友2sna6763', 'password': '654321'}" ]
}