{"name": "test_login_failed[data1]", "status": "passed", "attachments": [{"name": "log", "source": "cd70da05-3ca1-45f1-8852-173e65f3c196-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'name': '登录功能-异常登录-用户名错误', 'username': 'abc', 'password': '654321Ok'}"}], "start": 1609593761005, "stop": 1609593762271, "uuid": "6ea7f782-b633-49d7-8b6a-053b19aff675", "historyId": "28fbee3f7849e5c692210a9f12e7fe96", "testCaseId": "130e6dce60bc4ef9d882c5f0465dc1d6", "fullName": "cases.test_login.TestLogin#test_login_failed", "labels": [{"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "PC-20200718ELAI"}, {"name": "thread", "value": "4160-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_login"}]}