{"name": "test_login_failed[data1]", "status": "passed", "attachments": [{"name": "log", "source": "d0440185-dedc-4606-9110-28d92a4c4329-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'name': '登录功能-异常登录-用户名错误', 'username': 'abc', 'password': '654321Ok'}"}], "start": 1609591874545, "stop": 1609591875150, "uuid": "c247c60d-faa7-4e79-8d33-5f80c08770e7", "historyId": "28fbee3f7849e5c692210a9f12e7fe96", "testCaseId": "130e6dce60bc4ef9d882c5f0465dc1d6", "fullName": "cases.test_login.TestLogin#test_login_failed", "labels": [{"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "PC-20200718ELAI"}, {"name": "thread", "value": "7612-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_login"}]}