{"name": "test_login_success", "status": "broken", "statusDetails": {"message": "TypeError: 'module' object is not callable", "trace": "@pytest.fixture(scope='session')\n    def handler():\n>       driver = webdriver.chrome()  #调取chrom浏览器\nE       TypeError: 'module' object is not callable\n\ncases\\conftest.py:9: TypeError"}, "start": 1609210610695, "stop": 1609210610695, "uuid": "97712958-7b4b-4102-ab22-672dda384c2b", "historyId": "4de4eac7aa5437331edc4ae996ff58ee", "testCaseId": "a3db9ab94b753eb349ff93c7e366cb8a", "fullName": "cases.test_login.TestLogin#test_login_success", "labels": [{"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "PC-20200718ELAI"}, {"name": "thread", "value": "9228-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_login"}]}