{"name": "test_login_success", "status": "broken", "statusDetails": {"message": "TypeError: 'module' object is not callable", "trace": "@pytest.fixture(scope='session')\n    def handler():\n>       driver = webdriver.chrome()  #调取chrom浏览器\nE       TypeError: 'module' object is not callable\n\ncases\\conftest.py:9: TypeError"}, "start": 1609333895653, "stop": 1609333895653, "uuid": "cd643477-31be-42e6-9f1b-08454fc7bdf1", "historyId": "4de4eac7aa5437331edc4ae996ff58ee", "testCaseId": "a3db9ab94b753eb349ff93c7e366cb8a", "fullName": "cases.test_login.TestLogin#test_login_success", "labels": [{"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "PC-20200718ELAI"}, {"name": "thread", "value": "6860-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_login"}]}